title: mi sitio web sencillo
description: PÃ¡gina creada con jekyll y GitHub Pages 
# _config.yml

remote_theme: "jekyll/minima@1e8a445"
puglins:
- jekyll-remote-theme =add this line to the puglins list if you already have one
